// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDICM96Snn4vKUs-hUdfSB2DuSOWOdplo4',
    appId: '1:390884061029:web:c4002740e0414867c0fb8c',
    messagingSenderId: '390884061029',
    projectId: 'cube2nd',
    authDomain: 'cube2nd.firebaseapp.com',
    storageBucket: 'cube2nd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxi_DzLnN-w35LjDc5WetVeLM2DAdT6g',
    appId: '1:390884061029:android:b7d317087ce37796c0fb8c',
    messagingSenderId: '390884061029',
    projectId: 'cube2nd',
    storageBucket: 'cube2nd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Hh_dtBBb-KFoni4c6r4lnOP_m3EETKc',
    appId: '1:390884061029:ios:5988c987a62733f2c0fb8c',
    messagingSenderId: '390884061029',
    projectId: 'cube2nd',
    storageBucket: 'cube2nd.appspot.com',
    iosClientId: '390884061029-0nguclm1vlbu3ppqv068vhdh73gfa55j.apps.googleusercontent.com',
    iosBundleId: 'com.example.gofoods',
  );
}
